apiVersion: v1
kind: Service
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  type: NodePort
  ports:
  - port: 8000
    name: python-app
    nodePort: 32756
  selector:
    app: python-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
    spec:
      containers:
      - name: python
        image: python-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
